name: Build & Push dist to public repo

on:
  push:
    tags:
      - 'dev-*'

jobs:
  deploy-dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Lint (optional)
        run: npm run lint || echo "Lint skipped"

      - name: Build project
        run: npm run build:lib

      - name: Prepare dist repo
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.DIST_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git config --global user.name "github-actions"
          git config --global user.email "actions@bookiflex.com"

          git clone git@github.com:BookiFlex/plugin-widget-booking-dist.git dist-push
          cd dist-push

          rm -rf *
          cp -r ../dist/* .
          echo "dev build from: https://cdn.jsdelivr.net/gh/BookiFlex/plugin-widget-booking-dist@$GITHUB_REF_NAME/index.umd.js" > README.md
          git add .
          git commit -m "Dev build lib: $GITHUB_REF_NAME"
          git tag $GITHUB_REF_NAME || true
          git push origin main --tags
